services:
  webserver:
    image: ${BASE_IMAGE_WEBSERVER_NAME}-dev:${BASE_IMAGE_WEBSERVER_TAG}
    build:
      context: ${BASE_IMAGE_WEBSERVER_CONTEXT}

  php:
    image: ${BASE_IMAGE_PHP_NAME}-dev:${BASE_IMAGE_PHP_TAG}
    build:
      context: ${BASE_IMAGE_PHP_CONTEXT}
      target: dev