services:
  webserver:
    image: ${BASE_IMAGE_WEBSERVER_NAME}:${BASE_IMAGE_WEBSERVER_TAG}
    build:
      context: ${BASE_IMAGE_WEBSERVER_CONTEXT}
      args:
        TIME_ZONE: ${TIME_ZONE}

  php:
    image: ${BASE_IMAGE_PHP_NAME}:${BASE_IMAGE_PHP_TAG}
    build:
      context: ${BASE_IMAGE_PHP_CONTEXT}
      args:
        TIME_ZONE: ${TIME_ZONE}
        VERSION: ${PHP_VERSION}
        WORK_DIR: /var/www/app
        WWW_LISTEN: /sock/docker.sock
      target: production