# version: '3.8'

services:
# image: caddy
  proxy:
    build:
      dockerfile: ../.docker/caddy.Dockerfile
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./proxy.Caddyfile:/etc/caddy/Caddyfile
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    networks:
      - mynetwork

# image: openresty
  demo1:
    build:
      dockerfile: ../.docker/lua.apline-flat.Dockerfile
    volumes:
      - ./demo1/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/html/static
    networks:
      - mynetwork

# image: caddy
  demo2:
    build:
      dockerfile: ../.docker/caddy.Dockerfile
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - ./demo2.Caddyfile:/etc/caddy/Caddyfile
      - ./html:/var/html/static
    networks:
      - mynetwork

volumes:
  caddy_data:
  caddy_config:

networks:
  mynetwork:
    name: mynetwork
# driver: bridge
