services:
  webserver:
    build:
      dockerfile: ../../../../.docker/caddy/Dockerfile
#      args:
#        TZ: ${TZ}
    environment:
      HTML_CONTENT_FOLDER: ${HTML_CONTENT_FOLDER:-/var/www/html}
      PHP_WORK_DIR: ${PHP_WORK_DIR}
      PHP_PORT: ${PHP_PORT:-9000}
      PHP_CONTAINER: ${PHP_CONTAINER:-php}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443

  php:
    build:
      context: ../../../../.docker/php-fpm
      args:
        TZ: ${TZ}
        WORK_DIR: ${PHP_WORK_DIR}
    expose:
      - ${PHP_PORT}
    healthcheck:
      test: [ "CMD", "docker-healthcheck", "-connect" ]
#      test: [ "CMD", "docker-healthcheck", "-connect=9000" ]
#      test: [ "CMD", "docker-healthcheck", "-connect=/var/run/php/php-fpm.sock" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
  caddy_data:
  caddy_config:
