services:
  webserver:
    build:
      dockerfile: ../../../../.docker/caddy/Dockerfile
    environment:
      TZ: ${TZ}
      HTML_CONTENT_FOLDER: ${HTML_CONTENT_FOLDER:-/var/www/html}
      PHP_PORT: ${PHP_LISTEN_PORT}
      PHP_ROOT_FOLDER: ${PHP_WORK_DIR}
      PHP_CONTAINER_NAME: ${PHP_CONTAINER_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443

  php:
#    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: ../../../../.docker/php-fpm
      args:
        TZ: ${TZ}
        WORK_DIR: ${PHP_WORK_DIR}
        PORT: ${PHP_LISTEN_PORT}
#    ports:
#      - "${PHP_LISTEN_PORT}:${PHP_LISTEN_PORT}"
    expose:
      - ${PHP_LISTEN_PORT}
#    healthcheck:
#      test: [ "CMD", "docker-healthcheck", "--connect=${PHP_LISTEN_PORT}" ]
#      interval: 10s
#      timeout: 3s
#      retries: 3
#      start_period: 30s

volumes:
  caddy_data:
  caddy_config:
