services:
  webserver:
    build:
      dockerfile: ../../../../.docker/caddy/Dockerfile
    environment:
      HTML_CONTENT_FOLDER: ${HTML_CONTENT_FOLDER:-/var/www/html}
      PHP_PORT: ${PHP_PORT:-9000}
      PHP_CONTAINER: ${PHP_CONTAINER:-php}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443

  php:
    build:
      context: ../../../../.docker/php-fpm
      args:
        WORKING_DIR: ${PHP_WORKING_DIR:-/var/www/app}
    expose:
      - ${PHP_PORT:-9000}

volumes:
  caddy_data:
  caddy_config:
