services:
  webserver:
#    image: ${WEBSERVER_RUNTIME_IMAGE_NAME}:${WEBSERVER_RUNTIME_IMAGE_TAG}
    build:
      dockerfile: Dockerfile.caddy
      target: production
      args:
        IMAGE_NAME: ${BASE_IMAGE_WEBSERVER_NAME}
        IMAGE_TAG: ${BASE_IMAGE_WEBSERVER_TAG}
        HTML_SOURCE_PATH: ${WEBSERVER_ARG_SOURCE_PATH}
        HTML_TARGET_PATH: ${WEBSERVER_ARG_TARGET_PATH}
        PHP_FASTCGI: unix//${PHP_WWW_LISTEN}
        PHP_ROOT_PATH: ${PHP_ARG_TARGET_PATH}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - sock:${PHP_WWW_LISTEN_PATH}
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    depends_on:
      php:
        condition: service_healthy

  php:
#    image: ${PHP_RUNTIME_IMAGE_NAME}:${PHP_RUNTIME_IMAGE_TAG}
    build:
      dockerfile: Dockerfile.php
      target: production
      args:
        IMAGE_NAME: ${BASE_IMAGE_PHP_NAME}
        IMAGE_TAG: ${BASE_IMAGE_PHP_TAG}
        CONTENT_SOURCE_PATH: ${PHP_ARG_SOURCE_PATH}
        CONTENT_TARGET_PATH: ${PHP_ARG_TARGET_PATH}
    volumes:
      - sock:${PHP_WWW_LISTEN_PATH}
    healthcheck:
      test: [ "CMD", "docker-healthcheck", "--connect=${PHP_WWW_LISTEN}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  caddy_data:
  caddy_config:
  sock:
