services:
  webserver:
    build:
      target: dev
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - ./etc/caddy/sites-enabled/dev:/etc/caddy/sites-enabled
      - ./../../../../.content/html:$HTML_CONTENT_FOLDER

  php:
    volumes:
      - ./../../../../.content/php/plain:$PHP_WORK_DIR
