ARG IMAGE_NAME
ARG IMAGE_TAG

FROM ${IMAGE_NAME}:${IMAGE_TAG} as production
ARG CONTENT_SOURCE_PATH
ARG CONTENT_TARGET_PATH
COPY ${CONTENT_SOURCE_PATH} ${CONTENT_TARGET_PATH}
WORKDIR ${CONTENT_TARGET_PATH}

ARG IMAGE_TAG
ARG IMAGE_NAME
ENV BASE_IMAGE=${IMAGE_NAME}:${IMAGE_TAG}

FROM ${IMAGE_NAME}-dev:${IMAGE_TAG} as dev

ARG IMAGE_TAG
ARG IMAGE_NAME
ARG CONTENT_TARGET_PATH
WORKDIR ${CONTENT_TARGET_PATH}

ENV BASE_IMAGE=${IMAGE_NAME}-dev:${IMAGE_TAG}

