x-build-args-webserver: &build-args-webserver
  TIME_ZONE: Europe/Vienna
  PHP_WORK_DIR: /var/www/app
  PHP_FAST_CGI: unix//sock/docker.sock
  HTML_CONTENT_FOLDER: /var/www/html
x-build-args-php: &build-args-php
  WORK_DIR: /var/www/app
  TIME_ZONE: Europe/Vienna
  WWW_LISTEN: /sock/docker.sock

services:
# build base images
  build_webserver:
    image: ${BASE_IMAGE_WEBSERVER_NAME}:1.0.0
    build:
      context: ../../../../.docker/caddy
      args:
        TIME_ZONE: Europe/Vienna
    profiles:
      - build

  webserver:
    image: ${APPLICATION_DOCKER_IMAGE_PREFIX}-webserver:1.0.0
    build:
      dockerfile: Dockerfile.caddy
      target: prod
      args:
        IMAGE_NAME: ${BASE_IMAGE_WEBSERVER_NAME}
        IMAGE_TAG: ${BASE_IMAGE_WEBSERVER_TAG:-latest}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - sock:${PHP_WWW_LISTEN_PATH}
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    depends_on:
      php:
        condition: service_healthy

  php:
    build:
      context: ../../../../.docker/php-fpm
      args:
        <<: *build-args-php
    volumes:
      - sock:${PHP_WWW_LISTEN_PATH}
    healthcheck:
      test: [ "CMD", "docker-healthcheck", "--connect=${PHP_WWW_LISTEN}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  caddy_data:
  caddy_config:
  sock:
